language: go
go:
 - 1.7
install:
 - go get github.com/constabulary/gb/...
 - go get github.com/golang/lint/golint
 - go get github.com/fzipp/gocyclo
 - go get github.com/mattn/goveralls

script:
 - gb build github.com/matrix-org/dendrite/roomserver/roomserver && ./hooks/pre-commit
 - $HOME/gopath/bin/goveralls -service=travis-ci

notifications:
    webhooks:
        urls:
            - "https://scalar.vector.im/api/neb/services/hooks/dHJhdmlzLWNpLyU0MGtlZ2FuJTNBbWF0cml4Lm9yZy8lMjFhWmthbkFuV0VkeGNSSVFrV24lM0FtYXRyaXgub3Jn"
        on_success: change  # always|never|change
        on_failure: always
        on_start: never

